### ISSUE TITLE
Running OnlineSwiftPlayground locally - error: no such module 'OnlinePlayground'

### ISSUE THREAD

**Issue by arunkpatra** [krzyzanowskim/OnlineSwiftPlayground#18]
I tried to build and run locally. The UI came up fine and the backend started fine as well. I'm running on macOS Catalina, Xcode 11.1. However, when the call eventually lands up at the backend, what I get back in the UI is `error: no such module 'OnlinePlayground'`. Please see screenshot. Could you please help to shed some light and help me debug this?
<img width="1673" alt="Screen Shot 2019-10-18 at 4 19 04 PM" src="https://user-images.githubusercontent.com/2806069/67088739-8b548680-f1c3-11e9-9837-e82b5b3e2a7e.png">

**Comment by krzyzanowskim** [comment]
I guess it’s Catalina only issue? if so, then probably something with access - don’t know though

**Comment by arunkpatra** [comment]
Ok, I’ll try to build on Ubuntu.

**Comment by arunkpatra** [comment]
@krzyzanowskim You can close this issue. I realized that I had made an error in following the steps correctly.
