### ISSUE TITLE
Web http://online.swiftplayground.run/ is not working

### ISSUE THREAD

**Issue by matopeto** [krzyzanowskim/OnlineSwiftPlayground#33]
Hi 

the first.... great tool, I use it every time when i need something to check in swift. But now for long time web http://online.swiftplayground.run/ is not working

Can you please look at it

Thanks :)

**Comment by krzyzanowskim** [comment]
looking into it. Thank you for this report!

**Comment by krzyzanowskim** [comment]
it's live again! thank you

**Comment by matopeto** [comment]
Great, Thank you :)
