### ISSUE TITLE
Supports newer version of swift on web

### ISSUE THREAD

**Issue by matopeto** [krzyzanowskim/OnlineSwiftPlayground#35]
Hi

Thank you for great web. I am using it to check my code, and quick scripts

But can be possible to upgrade versions of swift on the web interface? You are providing only 5.0 and 5.1-release of swift, but today is  out version 5.5.2 (https://github.com/apple/swift/releases)

It may be handy in some situations

Thank you for considering it.

**Comment by krzyzanowskim** [comment]
done
