### ISSUE TITLE
Support embedding source in URL

### ISSUE THREAD

**Issue by OrkhanAlikhanov** [krzyzanowskim/OnlineSwiftPlayground#6]
The idea comes from typescript playground. If you open up the following
https://www.typescriptlang.org/play/index.html#src=console.log(%22Hello%22)%3B , you'll see that the source is `console.log("Hello");` which was embedded in hash as `#src=conso....`. So, you get point.

This way it would be really easy to share some runnable snippets to online.swiftplayground.run. Including the swift version as well it would be something like this:
http://online.swiftplayground.run/#v=4.2&src=print(%22Hello%22)

A bit related to #5

**Comment by agentcooper** [comment]
Turns out you can do it with the [data URL](https://developer.mozilla.org/en-US/docs/Web/HTTP/Basics_of_HTTP/Data_URIs): http://online.swiftplayground.run/?sourceURL=data:text/plain,print(%22wow%20this%20is%20loaded%20from%20the%20url%22).

**Comment by krzyzanowskim** [comment]
definitely! this feature needs more visibility though. Does anyone want to add information about it somewhere to the website?
