### ISSUE TITLE
No browser caching?

### ISSUE THREAD

**Issue by OrkhanAlikhanov** [krzyzanowskim/OnlineSwiftPlayground#7]
It seems on every refresh of the page, the same resources are downloaded over and over again. It would be more efficient to have caching on the client side, hence less CO<sub>2</sub> emission.

**Comment by krzyzanowskim** [comment]
is it? darn. Do you have an Idea how to improve it? I'm open to suggestions or changes to the sources.

**Comment by OrkhanAlikhanov** [comment]
To be honest, I am not good at cache control. It seems re-downloading resources does not happen on every refresh. When client accesses `app.js` sometimes server sends 307 response, `Temporary redirect` to [this link](http://10.64.42.65:8080/n/61cbc338b50943c8f17cda97f63ffb6b.js?q=m4KuiXDcR8pzipIXF5JuPfLrS8s4S%2FRomBqdbkkspa%2BjKeUIDXggzzKvVcKOnG6MeCNa6ZuEqhnUFkxul0KpczEOCwrdYbNvJMd1SXomN16I6D%2F5y2AHRkjzyiXtJGP9LSILGwg9RX1jjZSDYAbO4UkMj2sMUsOj5YirDuJIEzE%3D%7C1555074215%7Ca7525a1126bc3bb339455a9bc929af19&url=http%3A%2F%2Fonline.swiftplayground.run%2Fstatic%2Fapp%2Fapp.js) causing re-downloading 2.5mb file.

**Comment by arunkpatra** [comment]
I checked this today and the caching behavior seems to work correctly. I get hits in the disk and memory cache. Guess this issue may be closed.

**Comment by krzyzanowskim** [comment]
thank you! I'm closing this one then
